create table if not exists public.post_hearts (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (post_id, user_id)
);

create index if not exists post_hearts_post_id_idx on public.post_hearts (post_id);
create index if not exists post_hearts_user_id_idx on public.post_hearts (user_id);

alter table public.post_hearts enable row level security;

drop policy if exists "post_hearts_select_authenticated" on public.post_hearts;
create policy "post_hearts_select_authenticated"
on public.post_hearts
for select
to authenticated
using (true);

drop policy if exists "post_hearts_insert_own" on public.post_hearts;
create policy "post_hearts_insert_own"
on public.post_hearts
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "post_hearts_delete_own" on public.post_hearts;
create policy "post_hearts_delete_own"
on public.post_hearts
for delete
to authenticated
using (auth.uid() = user_id);

create table if not exists public.comment_hearts (
  id bigint generated by default as identity primary key,
  comment_id bigint not null references public.post_comments(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (comment_id, user_id)
);

create index if not exists comment_hearts_comment_id_idx on public.comment_hearts (comment_id);
create index if not exists comment_hearts_user_id_idx on public.comment_hearts (user_id);

alter table public.comment_hearts enable row level security;

drop policy if exists "comment_hearts_select_authenticated" on public.comment_hearts;
create policy "comment_hearts_select_authenticated"
on public.comment_hearts
for select
to authenticated
using (true);

drop policy if exists "comment_hearts_insert_own" on public.comment_hearts;
create policy "comment_hearts_insert_own"
on public.comment_hearts
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "comment_hearts_delete_own" on public.comment_hearts;
create policy "comment_hearts_delete_own"
on public.comment_hearts
for delete
to authenticated
using (auth.uid() = user_id);
