-- Extend existing posts table
alter table public.posts
add column if not exists note text,
add column if not exists heart_count integer not null default 0;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'posts_heart_count_nonnegative'
  ) then
    alter table public.posts
    add constraint posts_heart_count_nonnegative check (heart_count >= 0);
  end if;
end
$$;

-- Photos attached to a post (supports one or many photos)
create table if not exists public.post_photos (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  photo_url text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists post_photos_post_id_idx on public.post_photos (post_id);

-- Comments on posts
create table if not exists public.post_comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  comment_text text not null,
  created_at timestamptz not null default now()
);

create index if not exists post_comments_post_id_idx on public.post_comments (post_id);

-- Row Level Security
alter table public.post_photos enable row level security;
alter table public.post_comments enable row level security;

-- Posts policies
drop policy if exists "posts_select_authenticated" on public.posts;
create policy "posts_select_authenticated"
on public.posts
for select
to authenticated
using (true);

drop policy if exists "posts_update_own" on public.posts;
create policy "posts_update_own"
on public.posts
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "posts_delete_own" on public.posts;
create policy "posts_delete_own"
on public.posts
for delete
to authenticated
using (auth.uid() = user_id);

-- Post photos policies
drop policy if exists "post_photos_select_authenticated" on public.post_photos;
create policy "post_photos_select_authenticated"
on public.post_photos
for select
to authenticated
using (true);

drop policy if exists "post_photos_insert_own" on public.post_photos;
create policy "post_photos_insert_own"
on public.post_photos
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "post_photos_update_own" on public.post_photos;
create policy "post_photos_update_own"
on public.post_photos
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "post_photos_delete_own" on public.post_photos;
create policy "post_photos_delete_own"
on public.post_photos
for delete
to authenticated
using (auth.uid() = user_id);

-- Post comments policies
drop policy if exists "post_comments_select_authenticated" on public.post_comments;
create policy "post_comments_select_authenticated"
on public.post_comments
for select
to authenticated
using (true);

drop policy if exists "post_comments_insert_own" on public.post_comments;
create policy "post_comments_insert_own"
on public.post_comments
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "post_comments_update_own" on public.post_comments;
create policy "post_comments_update_own"
on public.post_comments
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "post_comments_delete_own" on public.post_comments;
create policy "post_comments_delete_own"
on public.post_comments
for delete
to authenticated
using (auth.uid() = user_id);
